version: 2
workflows:
  version: 2
  test_publish:
    jobs:
      - format
      - test
jobs:
  format:
    docker:
      - image: circleci/golang:1.14
    steps:
      - checkout
      - run:
          name: Check Format
          command: "! go fmt ./... 2>&1 | read"
  test:
    docker:
      - image: circleci/golang:1.14
    steps:
      - checkout
      - run: go test ./...
